remote_theme: mmistakes/minimal-mistakes@4.24.0
title: Hello Max!
title_separator: "|"
author: Max
excerpt_separator: <!--more-->
repository: maxmiliano/maxmiliano.github.io
teaser: /assets/images/
search: true
lunr:
  search_within_pages: true

paginate: 5
paginate_path: /page:num/

plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-feed
- jekyll-sso-tag
- jekyll-sitemap
- jekyll-spaceship
- jekyll-paginate

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    label: "comment"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      author: Max
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
