remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Hello Max!
description: Hello World! My name is Maxmiliano but you can call me Max. I’m a Software Engineer working with Ruby on Rails and a bunch of other technologies.
show_downloads: false
author: Max Braga
